[package]
name = "intiface-proxy"
version = "0.2.0"
authors = ["Runtime's Shady Backroom <76618880+runtime-shady-backroom@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.0", features = ["full"] }
warp = "0.3" # uses tokio 1.0
futures = { version = "0.3", default-features = false }
buttplug = { version = "2.0", features = ["websockets"] } # uses tokio 1.0.2
